image: clojure:alpine

cache:
  paths:
    - ~/.m2
    - /root/.m2
  untracked: true

up-to-date?:
  stage: test
  script:
    - lein ancient
  allow_failure: true

idiomatic?:
  stage: test
  script:
    - lein kibit
  allow_failure: true

test:
  stage: test
  script:
    - lein test
