cache:
  paths:
    - ~/.m2
    - /root/.m2
  untracked: true

up-to-date?:
  image: clojure:alpine
  stage: test
  script:
    - cd aggregator
    - lein ancient
  allow_failure: true

idiomatic?:
  image: clojure:alpine
  stage: test
  script:
    - cd aggregator
    - lein kibit
  allow_failure: true

test:
  image: clojure:alpine
  stage: test
  script:
    - cd aggregator
    - lein test
