stages:
  - build
  - test
  - analyze
  - deploy

services:
  - name: postgres:9.6-alpine
    alias: db
  - name: rabbitmq:3.6-alpine
    alias: broker

variables:
  POSTGRES_DB: aggregator
  POSTGRES_USER: aggregator
  POSTGRES_PASSWORD: "kI1BtN@rCbh2i6wg7EiEO*FwcdugST7s"
  RABBITMQ_DEFAULT_USER: "groot"
  RABBITMQ_DEFAULT_PASS: "iamgroot"

cache:
  paths:
    - ~/.m2
    - /root/.m2
  untracked: true


################################################################################
# Job-Templates

.job_template: &seed_db
  before_script:
    - apk add --no-cache postgresql-client
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - cd db/entrypoint
    - for f in *.sql ; do psql -h "db" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f $f ; done
    - cd ../../


################################################################################
# Jobs

up-to-date?:
  image: clojure:alpine
  stage: test
  script:
    - cd aggregator
    - lein ancient
  allow_failure: true

idiomatic?:
  image: clojure:alpine
  stage: test
  script:
    - cd aggregator
    - lein kibit
  allow_failure: true

test:
  <<: *seed_db
  image: clojure:alpine
  stage: test
  script:
    - cd aggregator
    - lein cloverage
