version: "3.1"

services:
  broker:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "8080:15672"  # web-access to management console
      - "5671-5672:5671-5672"  # for debugging, exposes RabbitMQs port to connect from localhost
    environment:
      - "RABBITMQ_DEFAULT_USER=${BROKER_USER}"
      - "RABBITMQ_DEFAULT_PASS=${BROKER_PASS}"

  aggregator:
    build: aggregator/
    volumes:
      - ~/.m2:/root/.m2  # cache leiningen dependencies
      - ./aggregator/:/code  # enable hot-code reloading
    ports:
      - "7777:7777"  # expose port to REPL
    links:
      - broker
    environment:
      - "BROKER_USER=${BROKER_USER}"
      - "BROKER_PASS=${BROKER_PASS}"
