version: "3.2"

services:

  aggregator:
    build: aggregator/
    restart: unless-stopped
    volumes:
      - ~/.m2:/root/.m2  # cache leiningen dependencies
      - ./aggregator/:/code  # enable hot-code reloading
      - ./aggregator/db/set1/:/code/db/entrypoint # Testdata. Use the set you need
    ports:
      - "7777:7777"  # expose port to REPL
      - "8888:8888" # ring dev server
    links:
      - search
      - dbas
      - dbas-db
    environment:
      - "ELASTICSEARCH_URL=http://search:9200"
      - "DB_USER=${DB_USER}"
      - "DB_PW=${DB_PW}"
      - "DB_PORT=${DB_PORT}"
      - "DB_NAME=${DB_NAME}"
      - "DBAS_HOST=dbas"
      - "ELASTICSEARCH_HOST=search"
      - "DB_HOST=dbas-db"
      - AGGREGATOR_NAME

  search:
    build: elasticsearch/
    restart: unless-stopped
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/synonyms_english.txt:/usr/share/elasticsearch/config/synonyms_english.txt
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.0
    restart: unless-stopped
    environment:
      ELASTICSEARCH_URL: http://search:9200
    ports:
      - "5601:5601"

  dbas:
    image: hhucn/dbas:latest
    restart: unless-stopped
    ports:
      - "4284:4284"
    links:
      - dbas-db:db 
    environment:
      - "DB_USER=${DB_USER}"
      - "DB_PW=${DB_PW}"
      - "DB_PORT=${DB_PORT}"
      - "DB_NAME=${DB_NAME}"
      - "DB_HOST=${DB_HOST}"
      - "AUTHN_SECRET=${AUTHN_SECRET}"
      - HHU_LDAP_SERVER
      - HHU_LDAP_BASE
      - HHU_LDAP_ACCOUNT_SCOPE
      - HHU_LDAP_ACCOUNT_FILTER
      - HHU_LDAP_ACCOUNT_FIRSTNAME
      - HHU_LDAP_ACCOUNT_LAST
      - HHU_LDAP_ACCOUNT_TITLE
      - HHU_LDAP_ACCOUNT_EMAIL
      - KEY_PATH
      - PUBKEY_PATH

  dbas-db:
    build: docker/db/
    restart: unless-stopped
    volumes:
      - ./docker/db/entrypoint:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
