version: "3.1"

services:
  broker_set2:
    image: rabbitmq:3.6-management-alpine
    environment:
      - "RABBITMQ_DEFAULT_USER=${BROKER_USER}"
      - "RABBITMQ_DEFAULT_PASS=${BROKER_PASS}"

  aggregator_set2:
    build: aggregator/
    volumes:
      - ~/.m2:/root/.m2  # cache leiningen dependencies
      - ./aggregator/:/code  # enable hot-code reloading
      - ./db/entrypoint/set2/:/code/db/entrypoint # Testdata. Use the set you need
    ports:
      - "7778:7777"  # expose port to REPL
      - "8889:8888" # ring dev server
    links:
      - broker_set2:broker
      - search_set2:search
      - dbas_set2:dbas
      - dbas-db_set2:dbas-db
    environment:
      - "BROKER_HOST=${BROKER_HOST}"
      - "BROKER_USER=${BROKER_USER}"
      - "BROKER_PASS=${BROKER_PASS}"
      - "DBAS_DB_USER=${DBAS_DB_USER}"
      - "DBAS_DB_PW=${DBAS_DB_PW}"
      - "DBAS_DB_PORT=${DBAS_DB_PORT}"

  search_set2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  dbas_set2:
    build: dbas/
    command: bash -c "sleep 8 && alembic upgrade head && pserve development.ini --reload"
    links:
      - dbas-db_set2:db
    environment:
      - "DBAS_DB_USER=${DBAS_DB_USER}"
      - "DBAS_DB_PW=${DBAS_DB_PW}"
      - "DBAS_DB_HOST=${DBAS_DB_HOST}"
      - "DBAS_DB_PORT=${DBAS_DB_PORT}"
      - "DBAS_AUTHN_SECRET=${DBAS_AUTHN_SECRET}"
    volumes:
      - ./dbas:/dbas

  dbas-db_set2:
    build: dbas/docker/db/
    volumes:
      - ./dbas/docker/db/entrypoint:/docker-entrypoint-initdb.d

networks:
  default:
    external:
      name: aggregator_default
