version: "3.1"

services:
  broker:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "15672:15672"  # web-access to management console
      - "5671-5672:5671-5672"  # for debugging, exposes RabbitMQs port to connect from localhost
    environment:
      - "RABBITMQ_DEFAULT_USER=${BROKER_USER}"
      - "RABBITMQ_DEFAULT_PASS=${BROKER_PASS}"

  aggregator:
    build: aggregator/
    volumes:
      - ~/.m2:/root/.m2  # cache leiningen dependencies
      - ./aggregator/:/code  # enable hot-code reloading
    ports:
      - "7777:7777"  # expose port to REPL
      - "8888:8888" # ring dev server
    links:
      - broker
      - search
      - dbas
      - dbas-db
    environment:
      - "BROKER_HOST=${BROKER_HOST}"
      - "BROKER_USER=${BROKER_USER}"
      - "BROKER_PASS=${BROKER_PASS}"
      - "DBAS_DB_USER=${DBAS_DB_USER}"
      - "DBAS_DB_PW=${DBAS_DB_PW}"
      - "DBAS_DB_PORT=${DBAS_DB_PORT}"

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  dbas:
    image: gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/dbas:development
    ports:
      - "4284:4284"
    links:
      - dbas-db:db
    environment:
      - "DBAS_DB_USER=${DBAS_DB_USER}"
      - "DBAS_DB_PW=${DBAS_DB_PW}"
      - "DBAS_DB_HOST=${DBAS_DB_HOST}"
      - "DBAS_DB_PORT=${DBAS_DB_PORT}"
      - "DBAS_AUTHN_SECRET=${DBAS_AUTHN_SECRET}"

  dbas-db:
    image: hhucn/dbas-database

  dbas-notifications:
    image: hhucn/dbas-notifications
    ports:
      - "5222:5222"
