version: "3.1"

services:
  broker:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "15672:15672"  # web-access to management console
      - "5671-5672:5671-5672"  # for debugging, exposes RabbitMQs port to connect from localhost
    environment:
      - "RABBITMQ_DEFAULT_USER=${BROKER_USER}"
      - "RABBITMQ_DEFAULT_PASS=${BROKER_PASS}"

  aggregator:
    build: aggregator/
    volumes:
      - ~/.m2:/root/.m2  # cache leiningen dependencies
      - ./aggregator/:/code  # enable hot-code reloading
    ports:
      - "7777:7777"  # expose port to REPL
      - "8888:8888" # ring dev server
    links:
      - broker
      - db
    environment:
      - "BROKER_HOST=${BROKER_HOST}"
      - "BROKER_USER=${BROKER_USER}"
      - "BROKER_PASS=${BROKER_PASS}"
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"

  db:
    image: postgres:9.6-alpine
    volumes:
      - ./db/entrypoint:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"  # again, just for debugging
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    ports:
      - "9200:9200"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

